image: node:latest  

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm --prefix backend/package.json install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: npm --prefix backend/package.json test