apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: backend-example
    context: backend
    sync:
      manual:
      # Sync all the javascript files that are in the src folder
      # with the container src folder
      - src: 'src/**/*.js'
        dest: .
deploy:
  kubectl:
      manifests:
        - k8s/postgres-db.yaml
        - k8s/backend.yaml
